# -*- coding: utf-8 -*-
"""Задание2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1490vMKwOyhJG5WcWTXmZKACTv-K5OSvH
"""

import numpy as np
import matplotlib.pyplot as plt

x=0.25
t=np.arange(0,np.pi/4,x)
y=4*np.e**(-3*t)*np.tan(t)
b=np.linspace(0.2,0.6,len(y))
plt.plot(b,y,lw=2,label='1')
plt.grid()
plt.xlabel('t')
plt.ylabel('U')
plt.title('График U от t')
plt.legend()